### ISSUE TITLE
调用openVideo播放视频，暂停再播放VideoActivity会闪退，内存泄漏

### ISSUE THREAD

**Issue by Unicellular-SU** [VenusCao/x5_webview_flutter#19]
WindowManager: android.view.WindowLeaked: Activity com.tencent.smtt.sdk.VideoActivity has leaked window com.tencent.mtt.video.internal.player.ui.an{266704f V.E...... ......ID 0,0-864,509} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:614)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:365)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
        at com.tencent.mtt.video.internal.player.d.v(H5VideoViewMounter.java:273)
        at com.tencent.mtt.video.internal.player.d.b(H5VideoViewMounter.java:193)
        at com.tencent.mtt.video.internal.player.d.a(H5VideoViewMounter.java:149)
        at com.tencent.mtt.video.internal.player.d$1.run(H5VideoViewMounter.java:124)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
D/ViewRootImpl@6350e09[VideoActivity]: dispatchDetachedFromWindow
D/ViewRootImpl@6350e09[VideoActivity]: dispatchDetachedFromWindow
D/InputEventReceiver: channel 'b239fd org.unicellular.otaku/com.tencent.smtt.sdk.VideoActivity (client)' ~ Disposing input event receiver.
    channel 'b239fd org.unicellular.otaku/com.tencent.smtt.sdk.VideoActivity (client)' ~NativeInputEventReceiver.
I/System.out: WonderPlayer:SmttCacheDownloader calls detatch()

**Comment by Unicellular-SU** [comment]
发现只有在默认横屏全屏的时候会闪退，当默认是竖屏全屏的时候，播放暂停没问题，把竖屏切换成横屏，然后再暂停再播放，就会还原成竖屏
![截图](https://user-gold-cdn.xitu.io/2019/11/29/16eb6849de2d2831?w=324&h=666&f=gif&s=4708769)

**Comment by VenusCao** [comment]
有问题就先用下面这个api吧，这个比较完善。
```
X5Sdk.openWebActivity("视频url", title: "视频名称");
```

**Comment by VenusCao** [comment]
screenMode 传102
