### ISSUE TITLE
与1.12版本创建的工程不兼容

### ISSUE THREAD

**Issue by ghost** [VenusCao/x5_webview_flutter#23]
```log
--------- beginning of crash
 03-25 11:04:15.623 13243 13243 E AndroidRuntime: FATAL EXCEPTION: main
 03-25 11:04:15.623 13243 13243 E AndroidRuntime: Process: com.xxxx.xxxxx, PID: 13243
 03-25 11:04:15.623 13243 13243 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx.xxxxx/com.example.    uhome.MainActivity}: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:   108)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:201)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6806)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old       FlutterView.
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at com.cjx.x5_webview.X5WebViewPlugin$Companion.registerWith(X5WebViewPlugin.kt:27)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at com.cjx.x5_webview.X5WebViewPlugin.registerWith(Unknown Source:2)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:39)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at com.example.uhome.MainActivity.configureFlutterEngine(MainActivity.kt:10)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.                               onAttach(FlutterActivityAndFragmentDelegate.java:185)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7224)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7213)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
 03-25 11:04:15.623 13243 13243 E AndroidRuntime:    ... 11 more
```
关键错误信息**The new embedding does not support the old FlutterView**

相关讨论

https://github.com/flutter/flutter/issues/40423

**Comment by ghost** [comment]
参考实现

https://github.com/shingohu/flutter_filereader

**Comment by VenusCao** [comment]
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.13.6 17G10021, locale zh-Hans-CN)
    • Flutter version 1.16.2 at /Users/cjx/flutter
    • Framework revision 58cad787d8 (2 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

我使用最新版本没出现你这个问题

**Comment by ghost** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.xxxx.xxx">
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

关键配置处，此处为新版plugin集成方式。plugin中的写法与该配置冲突。
