### ISSUE TITLE
android闪退

### ISSUE THREAD

**Issue by hongjie104** [VenusCao/x5_webview_flutter#5]
在执行这个方法的时候 X5Sdk.openWebActivity(url, title: title); 闪退了~
报错如下
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xingfei.ui/com.cjx.x5_webview.X5WebViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
E/AndroidRuntime(25733):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
E/AndroidRuntime(25733):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
E/AndroidRuntime(25733):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(25733):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
E/AndroidRuntime(25733):        at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(25733):        at android.os.Looper.loop(Looper.java:173)
E/AndroidRuntime(25733):        at android.app.ActivityThread.main(ActivityThread.java:6698)
E/AndroidRuntime(25733):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25733):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(25733):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/AndroidRuntime(25733): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
E/AndroidRuntime(25733):        at com.cjx.x5_webview.X5WebViewActivity.initView(X5WebViewActivity.kt:24)
E/AndroidRuntime(25733):        at com.cjx.x5_webview.X5WebViewActivity.onCreate(X5WebViewActivity.kt:20)
E/AndroidRuntime(25733):        at android.app.Activity.performCreate(Activity.java:7040)
E/AndroidRuntime(25733):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/AndroidRuntime(25733):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
```

求指导

**Comment by VenusCao** [comment]
检查你android  values下的 style 是否为noactionbar

**Comment by VenusCao** [comment]
还有不要使用AppCompat下的主题

**Comment by hongjie104** [comment]
> noactionbar

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
</resources>
```
style用的都是默认的，并没有做过任何修改

**Comment by VenusCao** [comment]
示例app会出现么

**Comment by hongjie104** [comment]
> 示例app会出现么

示例APP我手机装了，X5Sdk.openWebActivity 访问百度，算是正常吧，只是偶尔会出现错误提示，应该是因为百度页面里有下载百度app的链接导致。但是不会崩溃

**Comment by VenusCao** [comment]
那可能就是sdk版本的问题，你可以对照demo的bulid.gradle调整

**Comment by hongjie104** [comment]
额，我看了一下，demo和我的工程里的gradle都是3.2.1

**Comment by VenusCao** [comment]
android sdk,不是gradle

**Comment by hongjie104** [comment]
compileSdkVersion 和 targetSdkVersion 都设置成和demo一样的28了，错误依旧~

**Comment by VenusCao** [comment]
那你等下，我看看怎么调整一下

**Comment by VenusCao** [comment]
反正就是找不到actionbar，你把style改成有actionbar的主题试试，下个版本我处理一下

**Comment by VenusCao** [comment]
Theme.Black.NoTitleBar  改成 Theme.Black

**Comment by hongjie104** [comment]
好，多谢

**Comment by VenusCao** [comment]
试试新版本0.1.3

**Comment by hongjie104** [comment]
> 试试新版本0.1.3

新版本不会闪退了，非常感谢
