### ISSUE TITLE
进入web页面后，返回时报错

### ISSUE THREAD

**Issue by hongjie104** [VenusCao/x5_webview_flutter#6]
使用X5Sdk.openWebActivity进入web页面，按下返回键时，会有报错
```
W/System.err(18885): java.lang.NullPointerException: Attempt to invoke interface method 'com.tencent.smtt.export.external.extension.interfaces.IX5WebViewExtension com.tencent.smtt.export.external.interfaces.IX5WebViewBase.getX5WebViewExtension()' on a null object reference
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.tbsWebviewDestroy(Unknown Source:91)
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.destroy(Unknown Source:43)
W/System.err(18885):    at com.cjx.x5_webview.X5WebViewActivity.onDestroy(X5WebViewActivity.kt:60)
W/System.err(18885):    at android.app.Activity.performDestroy(Activity.java:7242)
W/System.err(18885):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
W/System.err(18885):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4492)
W/System.err(18885):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523)
W/System.err(18885):    at android.app.ActivityThread.-wrap5(Unknown Source:0)
W/System.err(18885):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
W/System.err(18885):    at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err(18885):    at android.os.Looper.loop(Looper.java:173)
W/System.err(18885):    at android.app.ActivityThread.main(ActivityThread.java:6698)
W/System.err(18885):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18885):    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err(18885):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
W/System.err(18885): java.lang.SecurityException: getDeviceId: Neither user 10647 nor current process has android.permission.READ_PHONE_STATE.
W/System.err(18885):    at android.os.Parcel.readException(Parcel.java:1951)
W/System.err(18885):    at android.os.Parcel.readException(Parcel.java:1897)
W/System.err(18885):    at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4823)
W/System.err(18885):    at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:994)
W/System.err(18885):    at com.tencent.smtt.utils.b.c(Unknown Source:21)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:209)
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.tbsWebviewDestroy(Unknown Source:116)
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.destroy(Unknown Source:43)
W/System.err(18885):    at com.cjx.x5_webview.X5WebViewActivity.onDestroy(X5WebViewActivity.kt:60)
W/System.err(18885):    at android.app.Activity.performDestroy(Activity.java:7242)
W/System.err(18885):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
W/System.err(18885):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4492)
W/System.err(18885):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523)
W/System.err(18885):    at android.app.ActivityThread.-wrap5(Unknown Source:0)
W/System.err(18885):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
W/System.err(18885):    at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err(18885):    at android.os.Looper.loop(Looper.java:173)
W/System.err(18885):    at android.app.ActivityThread.main(ActivityThread.java:6698)
W/System.err(18885):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18885):    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err(18885):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
W/System.err(18885): java.lang.SecurityException: getSubscriberId: Neither user 10647 nor current process has android.permission.READ_PHONE_STATE.
W/System.err(18885):    at android.os.Parcel.readException(Parcel.java:1951)
W/System.err(18885):    at android.os.Parcel.readException(Parcel.java:1897)
W/System.err(18885):    at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:535)
W/System.err(18885):    at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2348)
W/System.err(18885):    at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2330)
W/System.err(18885):    at com.tencent.smtt.utils.b.d(Unknown Source:21)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:213)
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.tbsWebviewDestroy(Unknown Source:116)
W/System.err(18885):    at com.tencent.smtt.sdk.WebView.destroy(Unknown Source:43)
W/System.err(18885):    at com.cjx.x5_webview.X5WebViewActivity.onDestroy(X5WebViewActivity.kt:60)
W/System.err(18885):    at android.app.Activity.performDestroy(Activity.java:7242)
W/System.err(18885):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
W/System.err(18885):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4492)
W/System.err(18885):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523)
W/System.err(18885):    at android.app.ActivityThread.-wrap5(Unknown Source:0)
W/System.err(18885):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
W/System.err(18885):    at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err(18885):    at android.os.Looper.loop(Looper.java:173)
W/System.err(18885):    at android.app.ActivityThread.main(ActivityThread.java:6698)
W/System.err(18885):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18885):    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err(18885):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
W/cr_AwContents(18885): WebView.destroy() called while WebView is still attached to window.
W/cr_ChildProcessConn(18885): onServiceDisconnected (crash or killed by oom): pid=22683
W/System.err(18885): javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
W/System.err(18885):    at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1143)
W/System.err(18885):    at javax.crypto.Cipher.doFinal(Cipher.java:1736)
W/System.err(18885):    at com.tencent.smtt.utils.o.c(Unknown Source:31)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.b(Unknown Source:83)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:0)
W/System.err(18885):    at com.tencent.smtt.sdk.a.c.run(Unknown Source:355)
W/System.err(18885): java.lang.NullPointerException: Attempt to get length of null array
W/System.err(18885):    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.b(Unknown Source:87)
W/System.err(18885):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:0)
W/System.err(18885):    at com.tencent.smtt.sdk.a.c.run(Unknown Source:355)
```
不过不影响使用

**Comment by VenusCao** [comment]
会闪屏重启么？你看看x5内核是否成功加载
使用openWebActivity 打开 'http://debugtbs.qq.com' 点击'合作方加载检测'
